language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t phamthaison/comp1640-client -f Dockerfile.dev .

script:
  - docker run -e CI=true phamthaison/comp1640-client npm run test -- --passWithNoTests

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'COMP-1640-client'
  env: 'Comp1640client-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-746188627003'
  bucket_path: 'COMP-1640-client'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
